### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by tire95** [LauriTahvanainen/Kirjoitusvirhekorjaaja#1]
Projekti ladattu 9.10. klo. 22:30

# Yleisiä kommenteja

Projekti vaikuttaa erittäin hyvältä! Koodi on selkeää, JavaDocs on tärkeimmissä (ja monimutkaisimmissa) kohdissa kirjoitettu selventämään metodeja, ja testejä on kattavasti. Tällä hetkellä näyttäisi siltä, että UI:n hiominen ja dokumentaatio ovat ainoat asiat jäljellä.

# Ohjelman suoritus

Huom! Ohjelman suorituksessa esiintyneet ongelmat voivat johtua siitä, että käytössäni ei ole fuksiläppäri eikä Linux; voi siis olla, että eri Java-versio ja Windows ovat ongelmien takana.

- Ensimmäisillä suorituskertayrityksillä ohjelma kaatui, koska "Virheellinen merkki annettu: '227'". En ole täysin varma mistä tämä ongelma johtui, ja sain tämän lopulta korjattua tyhjentämällä koko `sanalista.txt`-tiedoston ja lisäämällä sinne itse sanoja.
- Kun sain ohjelman käynnistettyä, JavaFX-ruutu oli täysin tyhjä. Tämä korjaantui poistamalla rivi 54

https://github.com/LauriTahvanainen/Kirjoitusvirhekorjaaja/blob/2bc2c225a85f581e38b685f6dd3bf48921008b49/Kirjoitusvirhekorjaaja/src/main/java/kvk/ui/Main.java#L54

- Kun ohjelmalle antaa syötteenä sanan ja painaa nappia "Tarkista kirjoitusvirhe", ohjelma antaa vaihtoehdot vasta, kun klikkaa tekstikenttää nappien alapuolella. Lisäksi jos ohjelmalla ei ole tarpeeksi korjausvaihtoehtoja, napit jäävät tyhjiksi. Mielestäni tämä ominaisuus olisi parempi toteuttaa esim. dropdown valikolla

# Koodi

- `TekstitiedostonKasittelija.java` ja `SuorituskykyTestaaja.java` käyttävät monia valmiita tietorakenteita. Suorituskyvyn testauksessa ymmärrän näiden käytön, mutta suosittelen keskustelemaan ohjaajien kanssa jos et ole vielä tehnyt niin, tai ainakin kirjoittamaan dokumentaatioon miksi valmiiden tietorakenteiden käyttö on tarpeellista
- Olit joissain kohdissa jättänyt `this`-avainsanan pois; tämä yhdenmukaisuuden puute on huono käytäntö ja tekee koodista vaikeampaa luettavaa

# Testit
- `ListaTest`:n testi `ListanKonstruktointi_OnnistuuEriTyypeilla` ja `PinoTest`:n testi `Pino_KonstruktointiEriTyyppeilla_Onnistuu` eivät testaa oikeastaan mitään. Yksi tapa testata näitä olisi esim. luoda String pino ja yrittää lisätä tähän numeroita ja odottaa että testi kaatuu
- `ListaTest` metodille `tarkistaPutkeenLisatytAlkiot` annetaan parametrinä `maara` jota ei käytetä
- `MerkkiSouluTauluTest` testit `LisaaHae_PerusTapaus_LisattuHaettavissaOikein` ja `LisaaHae_MontaLisatty_LisattuHaettavissaOikein` ovat täysin samat

**Comment by LauriTahvanainen** [comment]
Kiitän
